mkdir build
cd build
cmake .. -G "Visual Studio 17 2022" -D CMAKE_BUILD_TYPE=Release -A ARM64 -D USE_SSE4_1=OFF -D USE_SSE4_2=OFF -D USE_AVX=OFF -D USE_AVX2=OFF -D USE_AVX512=OFF -D USE_LZCNT=OFF -D USE_TZCNT=OFF -D USE_F16C=OFF -D USE_FMADD=OFF
pause